# Generated by Django 2.2.6 on 2019-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0002_campaign_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='keyword',
        ),
        migrations.AddField(
            model_name='campaign',
            name='Neg0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Neu0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='Pos0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='kw0',
            field=models.CharField(default='', max_length=50),
        ),
    ]
