# Generated by Django 2.2.6 on 2019-10-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0003_auto_20191030_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='kw0',
            new_name='keyword0',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Neg0',
            new_name='negative_percent0',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Neu0',
            new_name='neutral_percent0',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='Pos0',
            new_name='positive_percent0',
        ),
    ]
