# Generated by Django 2.2.6 on 2019-11-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0005_auto_20191102_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='keyword0',
            field=models.CharField(default='', max_length=50, verbose_name='Search Keywords'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
