# Generated by Django 2.2.6 on 2019-11-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0007_auto_20191103_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='negID0',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='posID0',
            field=models.CharField(default='', max_length=100),
        ),
    ]
