# Generated by Django 2.2.6 on 2019-11-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0008_auto_20191103_2144'),
        ('twitter_analysis', '0007_auto_20191102_1542'),
    ]

    operations = [
    ]
