# Generated by Django 2.2.6 on 2019-11-10 00:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0010_auto_20191109_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='negID1',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='negID2',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='posID1',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='posID2',
        ),
        migrations.AddField(
            model_name='campaign',
            name='negIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='campaign',
            name='posIDs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), null=True, size=None),
        ),
    ]
