# Generated by Django 2.2.6 on 2019-11-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0011_auto_20191110_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='negID0',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='posID0',
            field=models.CharField(default='', max_length=70),
        ),
    ]
