# Generated by Django 2.2.6 on 2019-11-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0012_auto_20191110_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='old_keyword',
            field=models.CharField(default='', max_length=50),
        ),
    ]
