# Generated by Django 2.2.6 on 2019-11-12 21:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0013_campaign_old_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='polarities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='campaign',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), null=True, size=None),
        ),
    ]
