# Generated by Django 2.2.6 on 2019-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0015_campaign_most_favorited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='most_favorited',
            field=models.CharField(default='', max_length=70),
        ),
    ]
