# Generated by Django 2.2.6 on 2019-11-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0016_auto_20191120_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_num_tweets',
            field=models.IntegerField(default=0),
        ),
    ]
