# Generated by Django 2.2.6 on 2019-11-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0017_campaign_total_num_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='total_num_neg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_num_pos',
            field=models.IntegerField(default=0),
        ),
    ]
