# Generated by Django 2.2.6 on 2019-11-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0018_auto_20191120_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='id_list',
            field=models.TextField(blank=True, verbose_name='Tweet IDs'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='keyword0',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Keywords'),
        ),
    ]
