# Generated by Django 2.2.6 on 2019-11-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0020_auto_20191128_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='id_list',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(verbose_name='Notes'),
        ),
    ]
