# Generated by Django 2.2.6 on 2019-11-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0021_auto_20191128_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='keyword0',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Keywords'),
        ),
    ]
