# Generated by Django 2.2.6 on 2019-11-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0022_auto_20191128_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='id_list',
            field=models.TextField(blank=True, verbose_name='Tweet IDs'),
        ),
    ]
