# Generated by Django 2.2.6 on 2019-11-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0023_campaign_id_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
