# Generated by Django 2.2.6 on 2019-11-30 20:30

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_analysis', '0029_auto_20191128_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='id_list',
            field=models.TextField(blank=True, max_length=400, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Tweet IDs'),
        ),
    ]
